/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'
import { Route as PipePaymentIndexRouteImport } from './routes/pipe/payment/index'
import { Route as PipeCartIndexRouteImport } from './routes/pipe/cart/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipePaymentIndexRoute = PipePaymentIndexRouteImport.update({
  id: '/pipe/payment/',
  path: '/pipe/payment/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipeCartIndexRoute = PipeCartIndexRouteImport.update({
  id: '/pipe/cart/',
  path: '/pipe/cart/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/pipe/cart': typeof PipeCartIndexRoute
  '/pipe/payment': typeof PipePaymentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/pipe/cart': typeof PipeCartIndexRoute
  '/pipe/payment': typeof PipePaymentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/pipe/cart/': typeof PipeCartIndexRoute
  '/pipe/payment/': typeof PipePaymentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category/$categoryId' | '/pipe/cart' | '/pipe/payment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category/$categoryId' | '/pipe/cart' | '/pipe/payment'
  id:
    | '__root__'
    | '/'
    | '/category/$categoryId'
    | '/pipe/cart/'
    | '/pipe/payment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  PipeCartIndexRoute: typeof PipeCartIndexRoute
  PipePaymentIndexRoute: typeof PipePaymentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipe/payment/': {
      id: '/pipe/payment/'
      path: '/pipe/payment'
      fullPath: '/pipe/payment'
      preLoaderRoute: typeof PipePaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipe/cart/': {
      id: '/pipe/cart/'
      path: '/pipe/cart'
      fullPath: '/pipe/cart'
      preLoaderRoute: typeof PipeCartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  PipeCartIndexRoute: PipeCartIndexRoute,
  PipePaymentIndexRoute: PipePaymentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
